### ISSUE TITLE
[docs] Readthedocs not setup yet

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#1]
Would be helpful to render the docs so that we can start with some docs-driven development.

**Comment by jnnr** [comment]
Need to setup a project hook with readthedocs.

**Comment by Bachibouzouk** [comment]
You can look at https://github.com/rl-institut/open_plan. You can build RTD automatically on PR, you just need to tick the option in the readthedocs account (under Special settings it is one tickbox, then click on the green "Save" button at the bottom of the page)

**Comment by gplssm** [comment]
> You can look at https://github.com/rl-institut/open_plan. You can build RTD automatically on PR, you just need to tick the option in the readthedocs account (under Special settings it is one tickbox, then click on the green "Save" button at the bottom of the page)

I did the same for https://github.com/OpenEnergyPlatform/open-MaStR. Sadly, the status check like in your example is not shown
![grafik](https://user-images.githubusercontent.com/8255114/95839400-4534f300-0d43-11eb-9852-015743fecfe6.png)
@Bachibouzouk do you have any further recommendation how to get this working?

Sorry for hijacking here, but seemed like a useful cross-project discussion!

**Comment by jnnr** [comment]
> You can look at https://github.com/rl-institut/open_plan. You can build RTD automatically on PR, you just need to tick the option in the readthedocs account (under Special settings it is one tickbox, then click on the green "Save" button at the bottom of the page)

Ah, I remember that it was a feature you could get on request some years ago. However, you will get a new version for each PR, which might be too much? Did start the build manually for now.
