### ISSUE TITLE
Define constants in config file for snakemake

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#108]
We could introduce a config file to set the solver, debug, logging, colors, labels, constants etc. This would address #78 and #84.

https://snakemake.readthedocs.io/en/stable/tutorial/advanced.html?#step-2-config-files

To use constants defined in the config file in the scripts directly, we could integrate snakemake into the scripts. So far, we have avoided this and passed all parameters to the scripts using command line arguments. This will blow up when we pass all constants explicitly. 

What does that mean in detail?

Instead of specifying the action of a rule using the `shell:` directive, we would use `script`. When calling the script with snakemake, snakemake is in the globals which allows to access the inputs with `snakemake.inputs` or the config with `config = snakemake.config`.

**Comment by henhuy** [comment]
I would suggest a simpler approach.
We can make use of simple `config.py` holding config settings, which can be imported by each script.
I just found [dynaconf](https://www.dynaconf.com/) which seems to be a very easy but also powerful tool to do this.
Settings are set up in settings.toml (or .secrets.toml for any passwords) and read from config.py. 
Example:
```
# settings.toml:

[optimize]
  iterations = 5
  [optimize.energysystem]
    components = 3
    busses = ["BE", "BB"]

# optimize.py

from config import settings

busses = settings.optimize.energysystem.busses
```

Do you agree?

**Comment by henhuy** [comment]
Added config options for script `optimize.py`.
This could be used as a how-to for other configurations.

**Comment by henhuy** [comment]
`config.py` has moved to oemof_b3.config module
