### ISSUE TITLE
Obsolete config files in project

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#124]
There are several config files for the project that are not used. If they are really obsolete, they should be removed before we release. Here is an overview:

* .travis.yml (we switched to github actions)
* .pylintrc (pylint is not part of the CI, only flake8)
* environment.yml (not up to date)
* requirements.txt (empty)

**Comment by henhuy** [comment]
you are right - those files are not needed. Will remove them.
About pylint: This can be very useful! I will run pylint on files I'm changing in the future.  This helps improving code.
