### ISSUE TITLE
Update to oemof v0.4

### ISSUE THREAD

**Issue by SabineHaas** [rl-institut/oemof-B3#126]
For using the new function `equate_flows_by_keyword` of oemof.solph we have to install the current branch (and later oemof v0.5). However, this will collide with `datapackage` (installed in `oemof.tabluar`) which still uses oemof v0.3 . 
I remember you saying that `datapackage` /  `oemof.tabluar` is planned to be upgraded on oemof v0.4, as well. Do you know when this would be?

There's also the following conflict. Does oemoflex work with the required pyomo versions of oemof-solph?
```The conflict is caused by:
    oemof-solph 0.4.5.dev0 depends on pyomo<5.7.3 and >=5.7.0
    oemoflex 0.0.0 depends on pyomo<5.6.9
```

_Originally posted by @SabineHaas in https://github.com/rl-institut/oemof-B3/issues/102#issuecomment-1034785454_

**Comment by jnnr** [comment]
Done with https://github.com/rl-institut/oemof-B3/pull/189, https://github.com/rl-institut/oemoflex/pull/57 and https://github.com/oemof/oemof-tabular/pull/21
