### ISSUE TITLE
Find sustainable solution for the requirements

### ISSUE THREAD

**Issue by MaGering** [rl-institut/oemof-B3#134]
After the merge of https://github.com/rl-institut/oemof-B3/pull/118, which according to the description was a "(dirty) fix", a sustainable solution is needed. The need arises, for example, because issue https://github.com/rl-institut/oemof-B3/issues/61 reappears after it has been fixed with PR https://github.com/rl-institut/oemof-B3/pull/96.

Background: The rendering of the points works with `sphinx-rtd-theme>=0.5.1` if this package is in the `install_requires` but not if it is listed in the `extras`.

To avoid this and other potential errors of this kind, a sustainable solution is required in which the package versions do not clash.

**Comment by henhuy** [comment]
Strange?! As `.readthedocs.yml` RTD uses requirements from `docs/docs_requirements.txt` where _sphinx_rtd_theme_ is listed.
Ah! But it is not pinned there. And from installation process (https://readthedocs.org/projects/oemof-b3/builds/16104801/) I can see that version 0.4.3 is installed.
I will pin version in docs_requirements.txt to >= 0.5.1
