### ISSUE TITLE
Add default data to empty scalars

### ISSUE THREAD

**Issue by SabineHaas** [rl-institut/oemof-B3#151]
create_empty_scalars now creates empty scalars file that serve as a template for input data.
To add emission_factors to specific components I had to manually add rows with `output_parameters` / `input_parameters` as their default is usually `{}`

For usability and also to make it more easy for new users to understand which parameters can be used, it would be nice to also add parameters that have default values.

**Comment by MaGering** [comment]
Done with https://github.com/rl-institut/oemof-B3/pull/307. To modify  `output_parameters` / `input_parameters` you'll need to set `create_empty_scalars.drop_default_scalars` in `settings.yaml` to `False`.
