### ISSUE TITLE
Add calculation of emission limit

### ISSUE THREAD

**Issue by SabineHaas** [rl-institut/oemof-B3#163]
Now the emission limit is provided with the scalars.

We have just discussed that we might want to use a range of emission reductions. 

todos:
- [x] adapt input data --> add reduction factor and an amount by which the emission limit is reduced due to sectors that are not included e.g. aircraft
- [x] add function that calculates the emission limit

proposal for names:

- `emissions_1990`
- `emission_reduction_factor` e.g. 0.8 or 0.95
- `emission_reduction_amount` unit e.g. kgCO2_eq

@jnnr do you agree?

**Comment by jnnr** [comment]
Thanks for your proposal! How about this (sketching the function as well):

`emission_limit =  (emissions_1990 -  emissions_not_modeled) * emission_reduction_factor`

**Comment by SabineHaas** [comment]
Fixed with #195 and #102
