### ISSUE TITLE
demandlib missing in installation requirements

### ISSUE THREAD

**Issue by SabineHaas** [rl-institut/oemof-B3#167]

**Comment by jnnr** [comment]
Because of a version conflict btw. pandas < 0.25, required by oemof 0.3.2, and pandas > 1.0.0, required by demandlib, we cannot include it in the list. @MaGering: Can you please add a one-liner to the docs and the readme, explaining that demandlib has to be installed manually?

**Comment by henhuy** [comment]
But how should this work?
Installing demandlib after installing oemof-b3, will install pandas>1.0.0, resulting in follwoing error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
oemof 0.3.2 requires numpy<1.18,>=1.7.0, but you have numpy 1.22.3 which is incompatible.
oemof 0.3.2 requires pandas<0.26,>=0.18.0, but you have pandas 1.4.1 which is incompatible.
oemof-b3 0.0.0 requires pandas==0.25.3, but you have pandas 1.4.1 which is incompatible.
Successfully installed demandlib-0.1.8 numpy-1.22.3 pandas-1.4.1
```
THi scannot be solved correctly - how does it work on your side?
I think either oemof-b3 or demandlib dependencies are not correct... (meaning that either oemof-b3 is capable of running pandas higher than 0.25 or demandlib capable of running with pandas < 1.0.0).

**Comment by MaGering** [comment]
> But how should this work? Installing demandlib after installing oemof-b3, will install pandas>1.0.0, resulting in follwoing error:
> 
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> oemof 0.3.2 requires numpy<1.18,>=1.7.0, but you have numpy 1.22.3 which is incompatible.
> oemof 0.3.2 requires pandas<0.26,>=0.18.0, but you have pandas 1.4.1 which is incompatible.
> oemof-b3 0.0.0 requires pandas==0.25.3, but you have pandas 1.4.1 which is incompatible.
> Successfully installed demandlib-0.1.8 numpy-1.22.3 pandas-1.4.1
> ```
> 
> THi scannot be solved correctly - how does it work on your side? I think either oemof-b3 or demandlib dependencies are not correct... (meaning that either oemof-b3 is capable of running pandas higher than 0.25 or demandlib capable of running with pandas < 1.0.0).

I have looked at this and it seems to me that the `pandas` version has never been pinned before your changes in PR https://github.com/rl-institut/oemof-B3/pull/128 @henhuy. [Here](https://github.com/rl-institut/oemof-B3/pull/128/files) you can compare the `setup.py` with the `pyproject.toml` file. What was the reason behind you pinning the version?

**Comment by henhuy** [comment]
This is because of oemof version used in oemof.tabular... see:
```
Because no versions of oemof match >0.3.1,<0.3.2 || >0.3.2
   and oemof (0.3.1) depends on pandas (>=0.18.0,<0.25), oemof (>=0.3.1,<0.3.2 || >0.3.2) requires pandas (>=0.18.0,<0.25).
  And because oemof (0.3.2) depends on pandas (>=0.18.0,<0.26), oemof (>=0.3.1) requires pandas (>=0.18.0,<0.26).
  Because oemoflex (rev dev) depends on oemof.tabular (rev dev)
   and oemof.tabular (rev dev) depends on oemof (>=0.3.1), oemoflex (rev dev) requires oemof (>=0.3.1).
  Thus, oemoflex (rev dev) requires pandas (>=0.18.0,<0.26).
  So, because oemof-b3 depends on both pandas (^1.0) and oemoflex (branch dev), version solving failed.
  ```
Could you provide `pip list` output - so that I can see what oemof version is installed?

**Comment by jnnr** [comment]
The documentation tells users that they have to install demandlib separately. I keep this issue open so we can properly include demandlib in the requirements as soon as the dependency conflict has been resolved.

**Comment by jnnr** [comment]
This has been resolved via https://github.com/rl-institut/oemof-B3/pull/189/commits/f866cc1ebda47de96959c5427f14fb4e4be5542e
