### ISSUE TITLE
Capacity costs for the expansion of transmission capacity are missing in the examples

### ISSUE THREAD

**Issue by c-moeller** [rl-institut/oemof-B3#17]
https://github.com/rl-institut/oemof-B3/blob/features/berlin-brandenburg/examples/simple_model/preprocessed/simple_model/data/elements/electricity-transmission.csv

**Comment by jnnr** [comment]
I had in mind that oemof.tabular's Link cannot be invested, but it seems that it is possible now. When running tranmission capacity expansion, this should be tested.

**Comment by jnnr** [comment]
We decided to set the capacities as fixed in the examples (done in 872445e).
