### ISSUE TITLE
Install oemoflex as developer version

### ISSUE THREAD

**Issue by SabineHaas** [rl-institut/oemof-B3#183]
I'd like to install oemoflex with `-e` but get dependency issues. 

Even `--force-reinstall` and `--ignore-installed` do not work.

```
ERROR: Cannot install oemof-b3==0.0.2.dev0 and oemoflex 0.0.0 (from /home/sabine/virtualenvs/oemoflex/oemoflex) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested oemoflex 0.0.0 (from /home/sabine/virtualenvs/oemoflex/oemoflex)
    oemof-b3 0.0.2.dev0 depends on oemoflex 0.0.0 (from git+https://****@github.com/rl-institut/oemoflex@dev)
```

Could this have to do with poetry @henhuy ?

**Comment by henhuy** [comment]
I will have a look

**Comment by henhuy** [comment]
Have you tried to uninstall oemoflex and install it with `pip install -e .`afterwards?

**Comment by henhuy** [comment]
same for me! but this is also due to changes in oemof.tabular I just did. Did not know that oemoflex points to dev.
See https://github.com/rl-institut/oemoflex/pull/57

**Comment by jnnr** [comment]
What I do is install oemoflex without from the local repo without updating dependencies `pip install --no-deps -e .`. However, in a conda environment, the repo is copied to the site-packages of the environment and is not updated when the local repo changes, such that I have to repeat the pip install. I wonder if there way to tell conda to point to the repo, not copy it.
