### ISSUE TITLE
Emission limit missing in additional_scalars.csv 

### ISSUE THREAD

**Issue by SabineHaas** [rl-institut/oemof-B3#184]
`emission_limit` is missing in `additional_scalars.csv` as scalars with empty field `name` are dropped beforehand. 

https://github.com/rl-institut/oemof-B3/blob/3db8e1a335260e61274f32b6b4c6dfbbca44ed28/scripts/build_datapackage.py#L281-L282

`additional_scalars.csv` cannot be saved before these lines as then `/preprocessed` does not exist, yet.

@jnnr are L281-L282 necessary?  If yes, I could just give emission limit a `name` as quick fix.

**Comment by jnnr** [comment]
Thanks for this issue! The reason why scalars with no name are dropped is that in parametrize_scalars, the index is set on name and var_name. We can move the dropping into the function parametrize_scalars, I guess. You could also move save_emission_limit up, so that it is executed first.

**Comment by SabineHaas** [comment]
I chose option 1 as `destination` is not only created in `to_csv_dir` but also the parameter `overwrite` is checked there. I did not want to change so much of the structure.

**Comment by jnnr** [comment]
Can we close this, @SabineHaas ?

**Comment by SabineHaas** [comment]
Yes, done with #102
