### ISSUE TITLE
Error running example scenarios in rule plot_dispatch

### ISSUE THREAD

**Issue by CatalinaPV** [rl-institut/oemof-B3#197]
Hi! I'm following the getting started procedure of oemof-B3 and when using snakemake to run the examples I get the following error. Do you know how this can be solved?

![grafik](https://user-images.githubusercontent.com/104063792/164193018-13b90824-8b9c-4a94-99ba-03f02d456b72.png)

Step to reproduce: _snakemake -j1 plot_all_examples_
Python version: 3.8.13
Thank you!

**Comment by jnnr** [comment]
I encountered this before. It happens because the respective dispatch plot contains no data. The plotting function is part of oemoflex and there is an open PR for that here https://github.com/rl-institut/oemoflex/pull/55
