### ISSUE TITLE
There is no basic model

### ISSUE THREAD

**Issue by Ludee** [rl-institut/oemof-B3#2]
Transfer basic oemof app from flexmex.

**Comment by Ludee** [comment]
What is the status of the simple model?
Only the documentation is missing?
The data needs to be downloaded from the OEP or is it using the API already?

**Comment by jnnr** [comment]
1. There are 3 scenarios for the simple model. They run through and can be integrated as examples in oemof-B3. 
2. Documentation is missing. Results have not been checked. 
3. The data is in the branch #11 and afaik also on the OEP. The code does not use the api yet to download them.
