### ISSUE TITLE
Problem with NaN in aggregate_scalars

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#226]
The function `aggregate_scalars` https://github.com/rl-institut/oemof-B3/blob/dev/oemof_b3/tools/data_processing.py#L383 has problems with NaNs. If e.g. I aggregate scalar data by region and `carrier` contains NaNs, the result will show NaN for carrier in all lines.

**Comment by henhuy** [comment]
Shouldn't this be addressed by [`groupby`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html) parameter `dropna` (new in version 1.1.0)?
I will check anyway
