### ISSUE TITLE
Use semicolon as delimiter

### ISSUE THREAD

**Issue by SabineHaas** [rl-institut/oemof-B3#252]
We have the convention to use semicolon as delimiter in oemof-b3 resources (raw data). However, it often occurs that by mistake we change them to comma. This happens e.g. when saving a csv file in Libre Office when at opening the file "comma" and "semicolon" were selected as delimiter. I had selected both of them as i was looking at pre- or postprocessed data, which is still using comma as delimiter. 

To prevent this in the future, especially to make it easier for new users **I suggest to use semicolon as delimiter everywhere where possible.**

Still with comma are files in directories:
- [ ] postprocessed
- [ ] preprocessed

**Comment by jnnr** [comment]
To fix this, we need to allow setting the delimiter in oemof.tabular and oemoflex.

**Comment by jnnr** [comment]
I opened a PR in oemoflex that allows to define the separator: https://github.com/rl-institut/oemoflex/pull/69

**Comment by jnnr** [comment]
The PR in oemoflex is merged. Now, the delimiter has to be set in config.config.settings and has to be set in the scripts build_datapackage and postprocess. Could you take over this one, @MaGering?
