### ISSUE TITLE
Snakemake: Problem with subdirectories in Windows 

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#26]
This bug has been described here already: https://github.com/snakemake/snakemake/issues/46

The current workaround described in pypsa-eur (https://pypsa-eur.readthedocs.io/en/latest/tutorial.html?highlight=windows#how-to-use-the-snakemake-rules) is to run snakemake with the flag `--keep-target-files`.

TODO: Add this to oemof-B3's docs.

**Comment by juliusmeier** [comment]
Proposal for the documentation:

When running snakemake with outputfiles in subfolders on Windows with 
```snakemake -j<NUMBER_OF_CPU_CORES>```
a MissingRuleException is raised. The process is unable to specify the output files in subfolders. This bug has been descibed here https://github.com/snakemake/snakemake/issues/46
The current workaround described in pypsa-eur (https://pypsa-eur.readthedocs.io/en/latest/tutorial.html?highlight=windows#how-to-use-the-snakemake-rules) is to run snakemake with the flag `--keep-target-files` to the command.
```snakemake -j<NUMBER_OF_CPU_CORES> --keep-target-files```
