### ISSUE TITLE
Scenarios not running (MissingRuleException)

### ISSUE THREAD

**Issue by MaGering** [rl-institut/oemof-B3#261]
Despite existing rules and correct data storage, the scenarios do not run anymore with

```
snakemake -j1 results/<scenario_name>/optimized
``` 

because of a MissingRuleException of

```
snakemake -j1 results/<scenario_name>/preprocessed
``` 
I was able to localize the error. It occurred with commit https://github.com/rl-institut/oemof-B3/commit/5477f0720e0d76aa3ed4e369201697f9ce4547a4 and more precisely in the changes made [here](https://github.com/rl-institut/oemof-B3/blob/5477f0720e0d76aa3ed4e369201697f9ce4547a4/Snakefile#L201) in the Snakefile.

**Comment by jnnr** [comment]
Thanks for reporting. The commit you point to aimed to separate the preprocessing of scenarios and examples. It worked when I commited it, but seems to be broken.

A quick dive into convinced me that snakemake does not properly process the regular expression in the wildcard constraint. I found this forum discussion which could help?: https://bioinformatics.stackexchange.com/questions/14991/snakemake-wildcard-constraints-reject-too-much
