### ISSUE TITLE
plot_scalar_results.py needs to be restructured

### ISSUE THREAD

**Issue by MaGering** [rl-institut/oemof-B3#278]
The script `plot_scalar_results.py` needs to be restructured since single scenarios are mixed with multiscenarios plots and the script is too extensive and cluttered.

Also a reason for issue https://github.com/rl-institut/oemof-B3/issues/262.

Single scenarios as the examples run with
```
snakemake -j1 plot_all_examples
```

won't work executing
```
    subplot_invest_out_multi_carrier(CARRIERS_WO_CH4)
    subplot_storage_invest_multi_carrier(CARRIERS_WO_CH4)
    subplot_flow_out_multi_carrier(CARRIERS_WO_CH4)
    subplot_demands(CARRIERS)
    subplot_energy_usage_multi_carrier(CARRIERS)
```

Plotting capacities with 
```
    plot_capacities()
```
 are dropped (cf. [this comment](https://github.com/rl-institut/oemof-B3/pull/276#issuecomment-1290628712))

**Comment by jnnr** [comment]
The original issue does not persist after #301. Shall we close this or is there more to be done, @MaGering?

**Comment by MaGering** [comment]
No, this can be closed. Thanks for fixing it! Tested it running `snakemake -j1 run_all_examples` and `snakemake -j1 results/2050-100-el_eff/plotted/scalars`.
