### ISSUE TITLE
Finalize oep integration

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#291]
Some steps are still todo. Here is an overview.

1. Upload all b3 results
https://openenergy-platform.org/dataedit/view/model_draft?query=oemof_b3
- [x] Setup new oemof-B3 environment and use raw data from server
- [x] test and merge https://github.com/rl-institut/oemof-B3/pull/244
- [x] merge dev into https://github.com/rl-institut/oemof-B3/pull/259
- [x] merge https://github.com/rl-institut/oemof-B3/pull/259
- [x] Produce all results
- [x] Clear all uploaded results
- [x] upload all results

2. Upload resources
- [x] Add rule that uploads resources or own raw data (reuse script for results) https://github.com/rl-institut/oemof-B3/pull/294

3. download resources
- [x] test and merge https://github.com/rl-institut/oemof-B3/pull/290 @jnnr 
- [x] merge dev into https://github.com/rl-institut/oemof-B3/pull/288
- [x] Implement download script into pipeline
- [x] Try to run pipeline with downloaded resources https://github.com/rl-institut/oemof-B3/pull/304

4. download raw
- [ ] write script similar to download resources or reuse? which only downloads own assumptions: Not done.
- [x] download external raw data from zenodo

**Comment by henhuy** [comment]
Which parts do you want me to do? :)

**Comment by jnnr** [comment]
> Which parts do you want me to do? :)

Thanks, @henhuy! You could take over 3, if you want.

**Comment by jnnr** [comment]
All done, apart from 4, which can be part of the next release 0.0.3.
