### ISSUE TITLE
Windows issue with snakemake is perhaps resolved

### ISSUE THREAD

**Issue by monika-o** [rl-institut/oemof-B3#318]
In the docs in the section "Snakemake on Windows" it says:

"When running snakemake with output files in subfolders on Windows with

snakemake -j<NUMBER_OF_CPU_CORES>

a MissingRuleException is raised. The process is unable to specify the output files in subfolders. This bug is an [open issue](https://github.com/snakemake/snakemake/issues/46) in snakemake."

This issue is closed now (since June 2021). It should be tested whether the problem has been resolved.

**Comment by Stefanie08** [comment]
Comparing the run of the rule `snakemake -j<NUMBER_OF_CPU_CORES>` with the workaround of Issue https://github.com/rl-institut/oemof-B3/issues/26, with `snakemake snakemake -j<NUMBER_OF_CPU_CORES> --keep-target-files`, the same output is generated. Therefore, this issue can be closed.
