### ISSUE TITLE
include data and assumptions

### ISSUE THREAD

**Issue by SabineHaas** [rl-institut/oemof-B3#36]
@jnnr I think we already have decided on using the "Datenbedarfstabelle". 
Have you tried to work with it in oemof-B3 already? I think it would be helpful to have use the same process on how to work with it for all of us: e.g. function to read and select data (which of the columns will form the parameter names etc.).

**Comment by jnnr** [comment]
Thanks for reminding me! It is on my list and I will take care of it soon.

**Comment by jnnr** [comment]
This has been settled with #57 (functions for data processing) and #43 (toy scenarios exemplifying the parametrization).
