### ISSUE TITLE
Conv_pp does not follow the template data structure

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#48]
#41 introduced a template data structure for all resources preprared in the model as well as all raw data that we compile ourselves.

conv_pp.csv is not produced according to this format yet. Please adapt the preparation such that it does.

**Comment by juliusmeier** [comment]
Do we use CSV with commas (,) or semicolons (;) as separation? Or does it not matter?

**Comment by juliusmeier** [comment]
What is the meaning of `id_scla` ?
