### ISSUE TITLE
Missing helper function for template data format 

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#49]
As it may used in many of the scripts, we should introduce functions that handle data which is in the template data format (introduced in #41).

In particular, we need implementations for these:

* df = load_scalars(path) 
* df = load_timeseries(path)
* save_scalars(df, path)
* save_timeseries(df, path)
* df_filtered = filter(df, key) (key could be e.g. scenario, region, carrier, tech, type, var_name)
* df_agg = aggregate(df, key) (key could be e.g region, carrier, tech,)

**Comment by jnnr** [comment]
Could you take care of this, @MaGering?

**Comment by MaGering** [comment]
For loading the scalars, I've been wondering which columns should be required. Running the examples I get a `scalars.csv` with the following columns:

- scenario
- name
- var_name
- var_value
- region
- type
- carrier
- tech

Does this mean, that the following columns are optional and would be added empty by the function `load_scalars`?

- id_scal
- var_unit
- reference
- comment

Same question for time series with the following parameters:

- id_ts
- region
- var_unit
- source
- comment
