### ISSUE TITLE
Feedin timeseries are missing

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#55]
The model needs feed-in timeseries for renewables (hourly capacity factors).

* [x] PV from renewables ninja / pvlib bzw. feedinlib
* [x] Wind from renewables ninja / windpowerlib bzw. feedinlib
* [x] RoR

**Comment by SabineHaas** [comment]
@jnnr 
Is there already a directory for the time series? Otherwise, I'd create `raw/time_series`?
For bringing the time series into the desired format we need to wait for #57 I assume

**Comment by SabineHaas** [comment]
For now I have placed them into  'Daten/raw/time_series' on our server

**Comment by jnnr** [comment]
> For now I have placed them into 'Daten/raw/time_series' on our server

That sounds reasonable, let's do it like this.

**Comment by jnnr** [comment]
@SabineHaas, is this resolved and can we close it?

**Comment by SabineHaas** [comment]
Yes, it was resolved with #68
