### ISSUE TITLE
Geopandas missing in setup.py

### ISSUE THREAD

**Issue by SabineHaas** [rl-institut/oemof-B3#56]
Had to install it to run the rule `prepare_conv_pp`

**Comment by jnnr** [comment]
Can you take care of this, @juliusmeier?

**Comment by juliusmeier** [comment]
On windows, geopandas cannot be installed via ```pip install geopandas```. Instead, one has to use ```conda install -c conda-forge geopandas```. But this does not work on Linux, does it?

**Comment by jnnr** [comment]
Geopandas should be installable with pip, but seems to need some special care https://geopandas.org/getting_started/install.html#installing-with-pip

How do we handle this? Shall we list geopandas under "extras_require" and document it?

**Comment by jnnr** [comment]
We could list geopandas under extras require and try the import in the script `prepare_conv_pp.py`, throwing a warning in case of an exception. This will help build the docs of the script.
