### ISSUE TITLE
[bug] Rule  `clean` removes scalars needed for `prepare_conv_pp`

### ISSUE THREAD

**Issue by SabineHaas** [rl-institut/oemof-B3#63]
I suggest to move the templates to another directory 'templates'.

Current situation: 
Cleaning results with `clean` and then running `prepare_conv_pp` leads to an error:
```
MissingInputException in line 42 of /home/sabine/virtualenvs/umas/oemof-B3/Snakefile:
Missing input files for rule prepare_conv_pp:
results/_resources/_scalar_template.csv
```

**Comment by jnnr** [comment]
I support that idea. Additionally, it may become usefull to refine the clean rule, e.g. allowing to clean only parts, like remove only one scenario, or remove all plots.
