### ISSUE TITLE
Column name scenario is confusing

### ISSUE THREAD

**Issue by SabineHaas** [rl-institut/oemof-B3#80]
The column name scenario in scalars and time series csv files is confusing. It is rather a "scenario-key" with which scalars and time series are selected for a specific scenario, see e.g. `toy-scenario.yml`:
https://github.com/rl-institut/oemof-B3/blob/518939f5a078617785ccb59928518019f86bfbbe/scenarios/toy-scenario.yml#L50-L59

We should rename to 
1. scenario_key
2. key
3. ...

Any opinions?

**Comment by jnnr** [comment]
scenario_key seems reasonable. I would like to discuss this with Hendrik when he joins the team.

**Comment by jnnr** [comment]
@henhuy agrees with scenario_key. Can you please adapt this,@MaGering?
* in oemof_b3/schema
* in the raw data

**Comment by MaGering** [comment]
Resolved with merge of PR #147.
