### ISSUE TITLE
oemof-B3 process should be explained in more detail in docs

### ISSUE THREAD

**Issue by SabineHaas** [rl-institut/oemof-B3#81]
This might help:

I understand the process to be the following (would be good to document in rtd)
- oemoflex defines default busses and components
- oemof-B3 overwrites and adds busses and components (component_attrs_update.yml, bus_attrs_update.yml); same for foreign keys
- in oemof-B3 one defines a scenario (.yml in `scenarios`) by selecting among others: busses and components from the available
- apart from that, a scenario filters scalars and time series by lets say "scenario-keys" (now confusingly named scenario --> issue #80)
	this is possible in several stages, see toy-scenario-2 `filter_scalars`

_Originally posted by @SabineHaas in https://github.com/rl-institut/oemof-B3/issues/69#issuecomment-950949164_

**Comment by SabineHaas** [comment]
Also nice for users: 

- [ ] how to add components: `component_attrs_update.yml`, `foreign_keys_update.yml`, add components to your scenario (`scalars.csv` and in `<scenario>.yml`)

**Comment by jnnr** [comment]
These infos are valuable. They could be stated in "model pipeline" next to "build datapackage" after restructuring #270.
Or they could be found in another chapter that tells users how to adapt the given scenarios to their needs.

**Comment by MaGering** [comment]
@monika-o and I found identified some improvements within PR https://github.com/rl-institut/oemof-B3/pull/279, that are related to this issue:

Regarding `scenario_key` in the raw data, you have picked up a good point. I took a look and saw that we don't have any guidance yet regarding scenario setup in the docs. I think for using `oemof-B3` it would be helpful to describe in a chapter "scenario requirements" or "scenario setup" how the scenario `yml` file is structured and how it is linked to the raw data. Questions that arise: What distinction in the scenario keys is minimally necessary for oemof-B3 to run? Which `scenario_key` belongs to which raw data file? So far there is only one sentence (deprecated though) at the bottom of [this paragraph](https://oemof-b3.readthedocs.io/en/latest/model_structure.html#oemof-b3-resources). I would open up a new issue with this, what do you think @monika-o ?

_Originally posted by @MaGering in https://github.com/rl-institut/oemof-B3/pull/279#discussion_r1011532479_

**Comment by jnnr** [comment]
@MaGering, can we close this one or is there something open still?

**Comment by MaGering** [comment]
Done with https://github.com/rl-institut/oemof-B3/pull/280.
