### ISSUE TITLE
Constants spread accross the script are hard to maintain

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#84]
We need a central config for constants that are used in the scripts. 

* how: A yml file
* filename: xxx?
* where: in oemof-B3/config
* how to import in scripts: load config in oemof-B3/__init__.py and import like `from oemof-B3.config import xxx`

**Comment by SabineHaas** [comment]
connected to #78, where I propose to add string representatives for strings that are constant (e.g. headers of templates, ...), 
could be placed in same location

**Comment by jnnr** [comment]
This has been implemented for most scripts. Todo:
* [ ] Check if all scripts' constants are defined in oemof_b3.config.settings
