### ISSUE TITLE
No logging yet

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#90]
oemof-b3's steps should be logged.

Could use snakemakes `log` directive. To capture the STDERR and STDOUT of the scripts, a redirection is necessary according to https://snakemake.readthedocs.io/en/stable/tutorial/advanced.html#step-5-logging.

**Comment by henhuy** [comment]
Acitivated logging in Snakefile. But as most of the scripts dont log, most log files are empty...

**Comment by henhuy** [comment]
A first logging advice can be found here: https://docs.python.org/3/howto/logging.html#when-to-use-logging
